# Mandatory fallbacks which are used when no or empty values have been provided.
locale = 'en'
destination = '/${locale}${path}'

[network]
# Network address for relocale.
# This defaults to localhost:10451.
address = 'localhost:10451'

[locales]
# This regular expression will set the locale to 'en' if the client's locale matches 'en', 'en-US', ...
en.alias = '^en-.+$'

de.alias = '^de-.+$'

# The destination path which will be redirected to.
# This is a template string with the following predefined parameters:
# * path: Original request path
# * locale: Current locale
de.destination = '/${locale}${path}'
